# Generated by Django 3.0.8 on 2020-07-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_apistep_apistep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitest',
            name='Product',
        ),
    ]
