# Generated by Django 3.0.8 on 2020-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcasestep',
            name='apptestdata',
            field=models.CharField(max_length=200, verbose_name='测试数据'),
        ),
    ]
